#!/bin/bash

rm build/turnkey-raspberrypints-13.0-wheezy-amd64-master-*.iso

make clean
make
if [ -f build/product.iso ]; then
   mv build/product.iso build/turnkey-raspberrypints-13.0-wheezy-amd64-master-$(date +"%Y%m%d").iso
fi
